server:
  port: 8081
  servlet:
    path: /w-paper
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.207.154:3306/w-paper2?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: tjc159753
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
          hibernate:
            enable_lazy_load_no_trans: true




